### ISSUE TITLE
[Server] Program login using email/password

### ISSUE THREAD

**Issue by Hantama237** [plumier/tutorial-monorepo-social-login#13]
connect the Login function with the UI

**Comment by Hantama237** [comment]
I have finish this ticket, please review my code, but I'm not using any router, I only use state, shall I make a pull request now? or I need to use router instead?

**Comment by ktutnik** [comment]
@Hantama237  yes please create pull request I will review.

**Comment by Hantama237** [comment]
@ktutnik  Ok done
